namespace AI_Study_Hub_v2.Services.Rag.Benchmarking;

public static class BenchmarkDataset
{
    public static IReadOnlyList<BenchmarkQuestion> All { get; } = Build().AsReadOnly();

    private static List<BenchmarkQuestion> Build() =>
    [
        // ── Definition (8) ──────────────────────────────────────────────────
        new("DEF-01", BenchmarkCategory.Definition, "What is RAG (Retrieval-Augmented Generation)?", true,
            "citation", null, null),
        new("DEF-02", BenchmarkCategory.Definition, "Define cosine similarity in the context of vector search.", true,
            "citation", null, null),
        new("DEF-03", BenchmarkCategory.Definition, "What is an embedding in natural language processing?", true,
            "citation", null, null),
        new("DEF-04", BenchmarkCategory.Definition, "Explain what a sliding window chunking strategy does.", true,
            "citation", null, null),
        new("DEF-05", BenchmarkCategory.Definition, "What is the difference between a vector and a scalar?", false,
            "general_knowledge", null, "A vector has both magnitude and direction; a scalar has only magnitude."),
        new("DEF-06", BenchmarkCategory.Definition, "Define what a foreign key is in relational databases.", false,
            "general_knowledge", null, null),
        new("DEF-07", BenchmarkCategory.Definition, "What is an API endpoint?", false,
            "general_knowledge", null, null),
        new("DEF-08", BenchmarkCategory.Definition, "Explain the concept of tokenization in LLMs.", false,
            "general_knowledge", null, null),

        // ── Comparison (8) ─────────────────────────────────────────────────
        new("CMP-01", BenchmarkCategory.Comparison, "Compare cosine similarity and Euclidean distance for text retrieval.", true,
            "citation", null, null),
        new("CMP-02", BenchmarkCategory.Comparison, "How does a sliding window chunking strategy differ from semantic chunking?", true,
            "citation", null, null),
        new("CMP-03", BenchmarkCategory.Comparison, "Compare Llama 3.3 70B and Gemini 2.5 Flash in terms of cost and capability.", true,
            "citation", null, null),
        new("CMP-04", BenchmarkCategory.Comparison, "What are the trade-offs between a smaller chunk size and a larger chunk size?", true,
            "citation", null, null),
        new("CMP-05", BenchmarkCategory.Comparison, "Compare synchronous and asynchronous programming.", false,
            "general_knowledge", null, null),
        new("CMP-06", BenchmarkCategory.Comparison, "What is the difference between HTTP and HTTPS?", false,
            "general_knowledge", null, null),
        new("CMP-07", BenchmarkCategory.Comparison, "Compare SQL and NoSQL databases.", false,
            "general_knowledge", null, null),
        new("CMP-08", BenchmarkCategory.Comparison, "What is the difference between supervised and unsupervised learning?", false,
            "general_knowledge", null, null),

        // ── Summary (8) ────────────────────────────────────────────────────
        new("SUM-01", BenchmarkCategory.Summary, "Summarize the key concepts of RAG in 3-5 sentences.", true,
            "citation", null, null),
        new("SUM-02", BenchmarkCategory.Summary, "Give me a brief summary of the document's main findings.", true,
            "citation", null, null),
        new("SUM-03", BenchmarkCategory.Summary, "What are the three main approaches to chunking discussed in the material?", true,
            "citation", null, null),
        new("SUM-04", BenchmarkCategory.Summary, "Summarize the installation and setup instructions.", true,
            "citation", null, null),
        new("SUM-05", BenchmarkCategory.Summary, "Summarize the water cycle.", false,
            "general_knowledge", null, null),
        new("SUM-06", BenchmarkCategory.Summary, "Give me a summary of the Python programming language.", false,
            "general_knowledge", null, null),
        new("SUM-07", BenchmarkCategory.Summary, "Summarize the causes of World War I.", false,
            "general_knowledge", null, null),
        new("SUM-08", BenchmarkCategory.Summary, "Summarize how REST APIs work.", false,
            "general_knowledge", null, null),

        // ── Diagram Explanation (8) ────────────────────────────────────────
        new("DIA-01", BenchmarkCategory.DiagramExplanation, "Explain this architecture diagram.", true,
            "citation", null, null),
        new("DIA-02", BenchmarkCategory.DiagramExplanation, "What does this flowchart represent?", true,
            "citation", null, null),
        new("DIA-03", BenchmarkCategory.DiagramExplanation, "Describe the relationships shown in this ER diagram.", true,
            "citation", null, null),
        new("DIA-04", BenchmarkCategory.DiagramExplanation, "What is the sequence of steps in this UML sequence diagram?", true,
            "citation", null, null),
        new("DIA-05", BenchmarkCategory.DiagramExplanation, "What trend does this bar chart show?", true,
            "citation", null, null),
        new("DIA-06", BenchmarkCategory.DiagramExplanation, "Describe the components in this system architecture diagram.", true,
            "citation", null, null),
        new("DIA-07", BenchmarkCategory.DiagramExplanation, "What does this pie chart tell us about the data distribution?", true,
            "citation", null, null),
        new("DIA-08", BenchmarkCategory.DiagramExplanation, "Explain the data flow shown in this diagram.", true,
            "citation", null, null),

        // ── Table Interpretation (4) ───────────────────────────────────────
        new("TBL-01", BenchmarkCategory.TableInterpretation, "What was the total revenue for Q3 according to the table?", true,
            "citation", null, null),
        new("TBL-02", BenchmarkCategory.TableInterpretation, "Which product had the highest sales in the table?", true,
            "citation", null, null),
        new("TBL-03", BenchmarkCategory.TableInterpretation, "What is the trend shown in the quarterly data table?", true,
            "citation", null, null),
        new("TBL-04", BenchmarkCategory.TableInterpretation, "Compare the values in column A and column B from the table.", true,
            "citation", null, null),

        // ── Missing Information (8) ────────────────────────────────────────
        new("MIS-01", BenchmarkCategory.MissingInformation, "What was the revenue in 2025?", true,
            "refusal", null, null),
        new("MIS-02", BenchmarkCategory.MissingInformation, "Who is the CEO of the company mentioned in the document?", true,
            "refusal", null, null),
        new("MIS-03", BenchmarkCategory.MissingInformation, "What are the stock prices for next quarter?", true,
            "refusal", null, null),
        new("MIS-04", BenchmarkCategory.MissingInformation, "How many employees does this company have in 2026?", true,
            "refusal", null, null),
        new("MIS-05", BenchmarkCategory.MissingInformation, "When will the next version be released?", true,
            "refusal", null, null),
        new("MIS-06", BenchmarkCategory.MissingInformation, "What is the email address of the support team?", true,
            "refusal", null, null),
        new("MIS-07", BenchmarkCategory.MissingInformation, "Who won the 2024 election according to these documents?", true,
            "refusal", null, null),
        new("MIS-08", BenchmarkCategory.MissingInformation, "What was the exact date of the event described in chapter 6?", true,
            "refusal", null, null),

        // ── Multi-source Retrieval (8) ─────────────────────────────────────
        new("MSR-01", BenchmarkCategory.MultiSourceRetrieval, "Compare the recommendations in document A and document B.", true,
            "citation", null, null),
        new("MSR-02", BenchmarkCategory.MultiSourceRetrieval, "What does document A say about chunking that document B does not?", true,
            "citation", null, null),
        new("MSR-03", BenchmarkCategory.MultiSourceRetrieval, "How do the two documents differ in their approach to embedding?", true,
            "citation", null, null),
        new("MSR-04", BenchmarkCategory.MultiSourceRetrieval, "What common conclusions do both documents share?", true,
            "citation", null, null),
        new("MSR-05", BenchmarkCategory.MultiSourceRetrieval, "Which document provides more detail about cosine similarity?", true,
            "citation", null, null),
        new("MSR-06", BenchmarkCategory.MultiSourceRetrieval, "Are there any contradictions between document A and document B?", true,
            "citation", null, null),
        new("MSR-07", BenchmarkCategory.MultiSourceRetrieval, "Combine the findings from both documents to give a complete picture.", true,
            "citation", null, null),
        new("MSR-08", BenchmarkCategory.MultiSourceRetrieval, "Which specific sections from each document address performance optimization?", true,
            "citation", null, null),

        // ── Architecture Understanding (8) ─────────────────────────────────
        new("ARC-01", BenchmarkCategory.ArchitectureUnderstanding, "Describe the high-level system architecture.", true,
            "citation", null, null),
        new("ARC-02", BenchmarkCategory.ArchitectureUnderstanding, "How does the authentication flow work in this system?", true,
            "citation", null, null),
        new("ARC-03", BenchmarkCategory.ArchitectureUnderstanding, "What components make up the data pipeline?", true,
            "citation", null, null),
        new("ARC-04", BenchmarkCategory.ArchitectureUnderstanding, "Explain the request lifecycle from user to database.", true,
            "citation", null, null),
        new("ARC-05", BenchmarkCategory.ArchitectureUnderstanding, "How does caching work in this architecture?", true,
            "citation", null, null),
        new("ARC-06", BenchmarkCategory.ArchitectureUnderstanding, "Describe the microservices shown and their interactions.", true,
            "citation", null, null),
        new("ARC-07", BenchmarkCategory.ArchitectureUnderstanding, "What is the role of the message queue in this system?", true,
            "citation", null, null),
        new("ARC-08", BenchmarkCategory.ArchitectureUnderstanding, "How does data flow from ingestion to the user-facing API?", true,
            "citation", null, null),
    ];
}
